export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGENERATE_ACCESS_TOKEN = 'REGENERATE_ACCESS_TOKEN';
export const UPDATE_USER_BASIC_INFO = 'UPDATE_USER_BASIC_INFO';