import { Inter } from "next/font/google";
import "@/styles/globals.css";
import QueryProvider from "../context/QueryContext";
import "@smastrom/react-rating/style.css";
import { AuthProvider } from "@/src/auth/context/auth/authContext";
import { dir } from "i18next";
import ToasterContext from "../context/ToasterContext";
import { languages } from "../i18n/settings";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <AuthProvider>
          <QueryProvider>
            <ToasterContext />
            <main className="main w-[100%] h-[100%]">{children}</main>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
